version: '3'
services:
  web:
    build: .
    external_links:
      - bd-pg:db-pg
    ports:
      - "80:80"
  database:
    image: "postgres"
    container_name: db-pg
    ports:
      - "5432:5432"