"""first

Revision ID: 11796ac6c243
Revises: 
Create Date: 2023-02-11 17:00:09.942549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11796ac6c243'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flags_cards',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('title')
    )
    op.create_index(op.f('ix_flags_cards_title'), 'flags_cards', ['title'], unique=True)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1', sa.Integer(), nullable=True),
    sa.Column('player2', sa.Integer(), nullable=True),
    sa.Column('round1', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['round1'], ['flags_cards.title'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=True)
    op.create_table('matches_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('round1', sa.Integer(), nullable=True),
    sa.Column('player_answer', sa.String(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['match'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_rounds_id'), 'matches_rounds', ['id'], unique=True)
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('tg_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state', sa.CHAR(length=1), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_matches_rounds_id'), table_name='matches_rounds')
    op.drop_table('matches_rounds')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_flags_cards_title'), table_name='flags_cards')
    op.drop_table('flags_cards')
    # ### end Alembic commands ###
