"""add more rounds2

Revision ID: 47c3ae219245
Revises: c8e26e89b6c3
Create Date: 2023-02-11 18:05:39.135552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c3ae219245'
down_revision = 'c8e26e89b6c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
