"""alter name round

Revision ID: 8dff44dd3c3e
Revises: 10fe85277cfd
Create Date: 2023-02-11 20:09:11.125078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dff44dd3c3e'
down_revision = '10fe85277cfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches_rounds', sa.Column('round', sa.Integer(), nullable=True))
    op.drop_column('matches_rounds', 'round1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches_rounds', sa.Column('round1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('matches_rounds', 'round')
    # ### end Alembic commands ###
