"""alter rounds

Revision ID: b43773d54caa
Revises: 81a9ce25761d
Create Date: 2023-02-11 18:18:55.131166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43773d54caa'
down_revision = '81a9ce25761d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('matches_round5_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_round4_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_round2_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_round3_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_round1_fkey', 'matches', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('matches_round1_fkey', 'matches', 'flags_cards', ['round1'], ['title'])
    op.create_foreign_key('matches_round3_fkey', 'matches', 'flags_cards', ['round3'], ['title'])
    op.create_foreign_key('matches_round2_fkey', 'matches', 'flags_cards', ['round2'], ['title'])
    op.create_foreign_key('matches_round4_fkey', 'matches', 'flags_cards', ['round4'], ['title'])
    op.create_foreign_key('matches_round5_fkey', 'matches', 'flags_cards', ['round5'], ['title'])
    # ### end Alembic commands ###
