"""add more rounds

Revision ID: c8e26e89b6c3
Revises: 11796ac6c243
Create Date: 2023-02-11 17:00:43.007792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e26e89b6c3'
down_revision = '11796ac6c243'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('round2', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('round3', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('round4', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('round5', sa.String(), nullable=True))
    op.create_foreign_key(None, 'matches', 'flags_cards', ['round2'], ['title'])
    op.create_foreign_key(None, 'matches', 'flags_cards', ['round3'], ['title'])
    op.create_foreign_key(None, 'matches', 'flags_cards', ['round5'], ['title'])
    op.create_foreign_key(None, 'matches', 'flags_cards', ['round4'], ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'round5')
    op.drop_column('matches', 'round4')
    op.drop_column('matches', 'round3')
    op.drop_column('matches', 'round2')
    # ### end Alembic commands ###
