"""alter name rounds

Revision ID: e654dd267ff9
Revises: b43773d54caa
Create Date: 2023-02-11 19:54:54.830122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e654dd267ff9'
down_revision = 'b43773d54caa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
